spring:
  application:
    name: ${APP_NAME:awstestingapp}

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/awstesting}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:tiger@data}
  #    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:update}
    show-sql: ${SHOW_SQL:true}
